spring:
  application:
    name: eureka-service
  cloud:
    config:
      uri: http://${SPRING_CONFIG_URI:localhost:8888}

server:
  port: 8761

# configure eureka to single instance
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false


# config eureka in cluster
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/